### ISSUE TITLE
How open .stats file created by -outlier flag

### ISSUE THREAD

**Issue by parinazbabaee** [reuter-lab/qatools-python#44]
Hi, 

I am using the following code to find the outliers of free surfer segmentation:

python3 qatools.py --subjects_dir /my/subjects --output_dir /my/output --outlier --screenshots-html

This code gives me a folder in my output called outliers. The outlier folder contains the following files:

all.aseg.stats
all.outliers.norms.stats
all.outliers.sample.nonpar.stats
all.outliers.sample.param.stats
all.regions.stats

However, I don't know how to read them in a table.

I already used the following code to read this:

asegstats2table -i /outliers/all.aseg.stats --tablefile /outliers/aseg_stats.txt  

but I get the following error:

Parsing the .stats files
Traceback (most recent call last):
  File "/Applications/freesurfer/7.4.0/python/scripts/asegstats2table", line 567, in <module>
    id_name_map, measurelist = parsed.parse(options.meas)
  File "/Applications/freesurfer/7.4.0/python/packages/fsbindings/legacy.py", line 509, in parse
    seg = strlst[1] # segmentation id is in the 2nd field
IndexError: list index out of range

I appreciate your help,
Parinaz.

**Comment by parinazbabaee** [comment]
The issue has been solved. I added ".csv" to the file's name, and then I could read it in a table.
